# Generated by Django 4.2.20 on 2025-04-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("S", "Solteiro(a)"),
                            ("C", "Casado(a)"),
                            ("D", "Divorciado(a)"),
                            ("V", "Viúvo(a)"),
                            ("U", "União Estável"),
                        ],
                        max_length=1,
                    ),
                ),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "endereco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.endereco",
                    ),
                ),
            ],
        ),
    ]
